name: voltspot
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #localization
  flutter_localizations:
    sdk: flutter
  #app icon
  flutter_launcher_icons: ^0.11.0


  go_router: ^16.1.0
  dartz: ^0.10.1
  get_it: ^7.6.4
  adaptive_theme: ^3.4.0
  fluttertoast: ^8.2.2
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0
  equatable: ^2.0.5
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  gradient_borders: ^1.0.0
  rxdart: ^0.28.0


flutter_icons:
  android: "ic_launcher"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  # then run
  # flutter pub get
  # flutter pub run flutter_launcher_icons:main
  # then you can delete package and photo and these code

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  bloc_test: ^9.1.7
  mocktail: ^1.0.3
  fake_async: ^1.3.1


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icon/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic